# Generated by Django 5.2.8 on 2026-01-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sublease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('address', models.TextField()),
                ('apartments_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('apartments_url', models.URLField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('sqft_living', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('pets', models.BooleanField(blank=True, null=True)),
                ('internet', models.TextField(blank=True, null=True)),
                ('washer_dryer_in_unit', models.BooleanField(blank=True, null=True)),
                ('washer_dryer_out_unit', models.BooleanField(blank=True, null=True)),
                ('furnished', models.BooleanField(blank=True, null=True)),
                ('housing_type', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('date_scraped', models.DateTimeField(blank=True, null=True)),
                ('additional_amenities', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
